import { Macondo, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
import { IdiomaProvider } from "@/context/IdiomaContext";

const macondo = Macondo({
  variable: "--font-macondo",
  subsets: ["latin"],
  weight: ["400"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Clínica Labirinto da Mente",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br" suppressHydrationWarning>
      <body
        className={`${macondo.variable} ${geistMono.variable} antialiased`}
      >
        <IdiomaProvider>
          <Providers>{children}</Providers>
        </IdiomaProvider>
      </body>
    </html>
  );
}